version: '3.4'
services:
  occ_solr:
    container_name: occ_solr
    image: solr:8.11
    ports:
     - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - jcg_example_core
volumes:
  data:
